export const issues = [
  {
    id: "UX-101",
    role: "Bệnh nhân",
    page: "Đặt lịch khám",
    type: "CTA và luồng thao tác",
    severity: "High",
    source: "Kiểm thử khả dụng",
    status: "Open",
    painPoint: "Người dùng không chắc bước tiếp theo sau khi chọn bác sĩ.",
    finding: "CTA đặt lịch bị chìm giữa nhiều thông tin phụ và chưa có trạng thái tiến trình.",
    recommendation: "Đưa CTA lên vùng nhìn đầu tiên, thêm step indicator và phản hồi sau khi chọn giờ.",
  },
  {
    id: "UX-102",
    role: "Bác sĩ",
    page: "Đánh giá bệnh nhân",
    type: "Thiếu chức năng",
    severity: "Medium",
    source: "Đánh giá theo vai trò",
    status: "In progress",
    painPoint: "Bác sĩ thiếu nơi xem và phản hồi toàn bộ đánh giá.",
    finding: "Khu bác sĩ trước đây chưa có màn tổng hợp review và bộ lọc sao.",
    recommendation: "Bổ sung trang đánh giá, tìm kiếm, phân bố sao và form phản hồi.",
  },
  {
    id: "UX-103",
    role: "Quản trị viên",
    page: "Duyệt bác sĩ",
    type: "Kiến trúc thông tin",
    severity: "Medium",
    source: "Phỏng vấn quản trị viên",
    status: "Open",
    painPoint: "Khó biết hồ sơ nào thiếu giấy tờ hoặc cần xử lý trước.",
    finding: "Danh sách thiếu badge trạng thái, mức ưu tiên và bộ lọc nhanh.",
    recommendation: "Thêm trạng thái hồ sơ, nhóm ưu tiên và bộ lọc theo thiếu thông tin.",
  },
  {
    id: "UX-104",
    role: "Bệnh nhân",
    page: "Thanh toán",
    type: "Phản hồi hệ thống",
    severity: "High",
    source: "Quan sát sử dụng",
    status: "Open",
    painPoint: "Người dùng không chắc thanh toán đã thành công hay chưa.",
    finding: "Phản hồi sau submit chưa đủ rõ và phụ thuộc vào alert.",
    recommendation: "Dùng màn xác nhận rõ ràng, mã lịch hẹn và hành động tiếp theo.",
  },
];

export const auditItems = [
  { criterion: "Hiển thị trạng thái hệ thống", area: "Thanh toán", score: 68, status: "Needs work" },
  { criterion: "Tính nhất quán và tiêu chuẩn", area: "Đăng nhập/Đăng ký", score: 82, status: "Pass" },
  { criterion: "Dễ nhận biết thay vì phải ghi nhớ", area: "Đặt lịch", score: 70, status: "Needs work" },
  { criterion: "Phòng tránh lỗi", area: "Duyệt hồ sơ", score: 74, status: "Needs work" },
  { criterion: "Tương phản và khả năng tiếp cận", area: "Chữ phụ", score: 76, status: "Review" },
];

export const recommendations = [
  {
    category: "CTA",
    title: "Một màn chỉ nên có một CTA chính",
    do: "Dùng màu nổi bật nhất cho hành động hoàn tất bước.",
    dont: "Không dùng nhiều nút cùng màu cho hành động chính và phụ.",
    example: "Trong chi tiết bác sĩ, Đặt lịch là CTA chính; Xem thêm là nút phụ.",
  },
  {
    category: "Phản hồi",
    title: "Luôn phản hồi sau hành động quan trọng",
    do: "Hiển thị trạng thái thành công, mã giao dịch và bước tiếp theo.",
    dont: "Không chỉ dùng alert rồi để người dùng tự suy đoán.",
    example: "Sau thanh toán, hiển thị phiếu khám và nút xem lịch hẹn.",
  },
  {
    category: "Biểu mẫu",
    title: "Form demo không chặn trải nghiệm",
    do: "Cho phép bỏ trống trường khi mục tiêu là trình bày flow.",
    dont: "Không bắt nhập dữ liệu không cần thiết trong demo usability.",
    example: "Login/register demo cho submit trực tiếp để kiểm tra luồng.",
  },
];
